-- Create the database
CREATE DATABASE Company;
GO

-- Use the created database
USE Company;
GO

-- Create the DEPARTMENT table
CREATE TABLE DEPARTMENT (
    DNAME VARCHAR(50) NOT NULL,
    DNUMBER INT PRIMARY KEY,
    MGRSSN CHAR(9),
    MGRSTARTDATE DATE
);
GO

-- Create the EMPLOYEE table
CREATE TABLE EMPLOYEE (
    FNAME VARCHAR(30) NOT NULL,
    LNAME VARCHAR(30) NOT NULL,
    SSN CHAR(9) PRIMARY KEY,
    BDATE DATE,
    ADDRESS VARCHAR(255),
    SEX CHAR(1) CHECK (SEX IN ('M', 'F')),
    SALARY DECIMAL(10,2),
    SUPERSSN CHAR(9),
    DNO INT NOT NULL
);
GO

-- Create the DEPT_LOCATIONS table
CREATE TABLE DEPT_LOCATIONS (
    DNUMBER INT,
    DLOCATION VARCHAR(100),
    PRIMARY KEY (DNUMBER, DLOCATION)
);
GO

-- Create the PROJECT table
CREATE TABLE PROJECT (
    PNAME VARCHAR(100) NOT NULL,
    PNUMBER INT PRIMARY KEY,
    PLOCATION VARCHAR(100),
    DNUM INT NOT NULL
);
GO

-- Create the WORKS_ON table
CREATE TABLE WORKS_ON (
    ESSN CHAR(9),
    PNO INT,
    HOURS DECIMAL(4,2),
    PRIMARY KEY (ESSN, PNO)
);
GO

-- Create the DEPENDENT table
CREATE TABLE DEPENDENT (
    ESSN CHAR(9),
    DEPENDENT_NAME VARCHAR(50),
    SEX CHAR(1) CHECK (SEX IN ('M', 'F')),
    BDATE DATE,
    RELATIONSHIP VARCHAR(50),
    PRIMARY KEY (ESSN, DEPENDENT_NAME)
);
GO



-- ADD FOREIGN KEY CONSTRAINTS

-- EMPLOYEE Table: Hierarchical relation (supervisor)
ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_SUPERSSN 
FOREIGN KEY (SUPERSSN) REFERENCES EMPLOYEE(SSN);
GO

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_DNO 
FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER);
GO

-- DEPARTMENT Table: Manager relation
ALTER TABLE DEPARTMENT 
ADD CONSTRAINT FK_MGRSSN 
FOREIGN KEY (MGRSSN) REFERENCES EMPLOYEE(SSN);
GO

-- DEPT_LOCATIONS Table
ALTER TABLE DEPT_LOCATIONS 
ADD CONSTRAINT FK_DEPT_LOC 
FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER);
GO

-- PROJECT Table
ALTER TABLE PROJECT 
ADD CONSTRAINT FK_DNUM 
FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUMBER);
GO

-- WORKS_ON Table: Employee and Project relations
ALTER TABLE WORKS_ON 
ADD CONSTRAINT FK_WO_ESSN 
FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN);
GO

ALTER TABLE WORKS_ON 
ADD CONSTRAINT FK_WO_PNO 
FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER);
GO

-- DEPENDENT Table: Employee relation
ALTER TABLE DEPENDENT 
ADD CONSTRAINT FK_DEPENDENT_ESSN 
FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN);
GO